from selene import browser, be, have, command
from selenium.webdriver import Keys
def test_successful_submit():
    browser.open('/automation-practice-form')
    browser.element('#firstName').should(be.blank).type('Evgenii')
    browser.element('#lastName').should(be.blank).type('Li')
    browser.element('#userEmail').should(be.blank).type('testacc@rambler.ru')
    browser.element('[for=gender-radio-1]').click()
    browser.element('#userNumber').should(be.blank).type('7999888776')
    browser.element('#dateOfBirthInput').click()
    browser.element('.react-datepicker__month-select').click()
    browser.element('.react-datepicker__month-select [value="2"]').click()
    browser.element('.react-datepicker__year-select').click()
    browser.element('.react-datepicker__year-select [value="1999"]').perform(command.js.scroll_into_view).click()
    browser.element('.react-datepicker__day--022').click()
    browser.element('#subjectsInput').should(be.blank).type('m').press_enter()
    browser.element('#subjectsInput').type('c').send_keys(Keys.ARROW_DOWN).send_keys(Keys.ARROW_DOWN).press_enter()
    browser.element('#subjectsInput').type('e')
    browser.element('#react-select-2-option-4').click()
    browser.element('[for=hobbies-checkbox-2]').click()
    browser.element('[for=hobbies-checkbox-3]').click()
    browser.element('#uploadPicture').send_keys('/home/evgeniili/IdeaProjects/qa_guru_7_5/tests/resources/test.png')
    browser.element('#currentAddress').should(be.blank).type('Odesskaya, bld. 24, appt. 23')
    browser.element('#react-select-3-input').type('u').press_enter()
    browser.element('#react-select-4-input').type('').send_keys(Keys.ARROW_DOWN).press_enter()
    browser.element('#submit').click()
